config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :user, only: [:new, :create]

  resources :categories


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category <  ApplicationRecord
  
 validates :category_name, presence: true
 validates :description, presence: true
 
end

app/models/user.rb
class User <  ApplicationRecord
  
  has_secure_password

   enum role: { user: 0, admin: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

# GET /categories or /categories.json
def index
 @category = Categorie.all
end

# GET /categories/1 or /categories/1.json


# GET /categories/1/edit
def edit 
end


def show
end

def new 
@category = Category.new
end

# POST /categories or /categories.json
def create(category_params)
@category = Category.new(category_params)
respond_to do |format| 
  if @category.save
     format.json {render :show}
     puts "Category saved"
  else
    puts "Failed to save the category"
  end
end
end


# PATCH/PUT /categories/1 or /categories/1.json
def update 
@category = Category.update(params[:id])
respond_to do |format|
if @category.update!
  format.json {render :show, status: :ok}
else
format.json {render :edit, notice: "Failed to edit the category"}
end
end
end

#Delete All
def delete_all

@category = Category.all

respond_to do |format|

if @category.delete_all!
format.html {notice: "All Categories successfully deleted"}
format.json {head :no_content}
end
format.html {notice: "Unable to delete the post"}
end

# DELETE /categories/1 or /categories/1.json
def delete
@category = Category.find(params[:id])
respond_to do |format|
if @category.destroy!
format.html {notice: "Category successfully deleted"}
format.json {head :no_content}
else
format.html {notice: "Unable to delete the post"}
end
end
end


# Only allow a list of trusted parameters through.
private

def category_params 

params.require(:category).permit(:category_name, :description)

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new 
    @user = User.new
  end

  def create(user_params)

    @user = User.new(user_params)
    if @user.save
         
      session[:user_id] = @user.id
      redirect_to root_path, flash: { success: "Signed up successfully" }
    
    else

      flash[:notice] = "Failed to Register"
      render :new
    
    end

  end

  private

  def user_params

    params.require(:user).permit(:email, :password, :role) 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/category/new.html.erb
<h1>Add Category</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wizcommerse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/new.html.erb
<!-- app/views/registrations/new.html.erb -->
<div class="text-center">
  <h1>Registration</h1>

  <%= form_with(model: @user, url: user_index_path, local: true) do |f| %>

    <!-- Display error message of form -->
    <% if f.object.errors.full_messages.any? %>
      <ul class='error'>
        <% f.object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <!-- Field of registration form -->
    <div class='row'>
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: 'Please enter email id' %>
    </div>
  
    <div class='row'>
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: 'Please enter password' %>
    </div>

    <div class='row'>
     <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, placeholder: 'Please enter password confirmation' %>
    </div>

    <div class='row'>
      <%= f.submit 'Sign Up' %>
    </div>
  <% end%>
</div>